"""Rewrite the gate table in docs/ACCURACY.md from the registry. D-061.

The failure this closes is one the document was committing against itself.

docs/ACCURACY.md has said since P0:

    This page is generated from `bench/results/latest.json`. There is no second
    place to type a precision figure, so a number here that is not in that file
    cannot happen.

That was not true. Nothing generated the page. The table under "Finding types and
their gates" was typed by hand in P0 and edited by hand afterwards, which is
exactly the second place the sentence promises does not exist. By P9 it had
drifted in all three ways a hand-maintained table drifts:

  * it listed fifteen finding types while the registry declared sixteen, so
    `documentation_gap` shipped with no published gate at all;
  * its Status column read "awaiting P2", "awaiting P3", "awaiting P5" - phase
    labels that stopped meaning anything four phases earlier; and
  * nothing anywhere could tell you it had drifted, because no test compared the
    published number to the measured one.

The third is the serious one. A precision figure typed into a document is a
marketing claim wearing a measurement's clothes, and this project's entire
argument is that those are different things. The registry already reads
`bench/results/latest.json` and already computes `enabled_for_paid` from it, so
the table can be derived rather than asserted - and once it is derived, the
sentence at the top of the page becomes a description of the mechanism instead
of a promise about our future behaviour.

    bench/results/latest.json -> registry.FINDING_TYPES -> docs/ACCURACY.md
      -> apps/web/src/generated/accuracy.ts -> /accuracy

One direction, no manual step. `--check` is wired into the test suite
(tests/test_accuracy_doc.py), so editing the table by hand fails the build with
the diff printed, and editing a threshold in the registry updates the published
page on the next run.

Usage:

    python scripts/sync_accuracy_table.py           rewrite the table in place
    python scripts/sync_accuracy_table.py --check   fail if it has drifted
"""

from __future__ import annotations

import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "packages" / "engines" / "src"))

from tirekick_engines import registry  # noqa: E402

DOC_PATH = REPO_ROOT / "docs" / "ACCURACY.md"

#: The table lives between these. They are HTML comments so they are invisible in
#: any markdown renderer, including the one the product ships on /accuracy, and
#: they name the script so whoever finds a surprising diff knows what wrote it.
BEGIN = "<!-- generated by scripts/sync_accuracy_table.py - do not edit by hand -->"
END = "<!-- end generated -->"


def _measured(spec: registry.FindingTypeSpec) -> str:
    if spec.measured_precision is None:
        return "not measured"
    return f"{spec.measured_precision:.2f}"


def _gate(spec: registry.FindingTypeSpec) -> str:
    """A zero gate is not a gate of zero; it means precision does not apply.

    Two types are summaries rather than judgments - complaint volume, and
    arithmetic on comps the buyer chose - and scoring them for precision would
    be scoring the wrong thing. Printing "0.00" would read as the loosest gate
    on the page rather than the absence of one, which is the more flattering
    misreading and therefore the one to avoid.
    """
    if spec.precision_gate <= 0.0:
        return "n/a"
    return f"{spec.precision_gate:.2f}"


def render_table() -> str:
    """The table exactly as it should appear in the document."""
    lines = [
        BEGIN,
        "",
        "| Finding type | Precision gate | Measured | n | In paid reports | Status |",
        "|---|---|---|---|---|---|",
    ]
    for spec in registry.FINDING_TYPES.values():
        paid = "yes" if spec.enabled_for_paid else "no"
        lines.append(
            f"| {spec.type} | {_gate(spec)} | {_measured(spec)} | {spec.n} "
            f"| {paid} | {spec.status} |"
        )
    lines.extend(["", END])
    return "\n".join(lines)


def _split(text: str) -> tuple[str, str]:
    """Everything before the marked region, and everything after it."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"error: {DOC_PATH} has no generated region.\n"
            f"  expected a block delimited by:\n    {BEGIN}\n    {END}\n"
            f"  Re-add the markers around the gate table; this script will not "
            f"guess where it goes."
        )
    if end < start:
        raise SystemExit(f"error: {DOC_PATH} has its generated-region markers inverted")
    return text[:start], text[end + len(END) :]


def rendered_document() -> str:
    before, after = _split(DOC_PATH.read_text(encoding="utf-8"))
    return before + render_table() + after


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    check = args == ["--check"]
    if args and not check:
        print(__doc__)
        return 2

    current = DOC_PATH.read_text(encoding="utf-8")
    wanted = rendered_document()

    if current == wanted:
        print(f"  {DOC_PATH.relative_to(REPO_ROOT)}: gate table matches the registry")
        return 0

    if check:
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            wanted.splitlines(keepends=True),
            fromfile="docs/ACCURACY.md (committed)",
            tofile="docs/ACCURACY.md (from registry)",
        )
        sys.stdout.writelines(diff)
        print(
            "\nerror: the published gate table does not match the measured one.\n"
            "  Run: python scripts/sync_accuracy_table.py",
            file=sys.stderr,
        )
        return 1

    DOC_PATH.write_text(wanted, encoding="utf-8")
    print(f"  rewrote the gate table in {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
